#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework.cloud.gateway: DEBUG
server:
  port: 8888
eureka:
  client:
     #下面两项没有代码提示
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true    
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
spring:
  cloud:
    gateway:
      routes:
      - id: bulletscreen-rest
        uri: lb://bullet
        predicates:
        - Path=/rest/**
      - id: bulletscreen-socket
        uri: lb:ws://bullet
        predicates:
        - Path=/bullet/**
  sleuth:
     sampler:
       percentage: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always #默认是never